@startuml

title __COMPONENTS's Class Diagram__\n

  namespace enstabretagne.simulation.components {
    interface enstabretagne.simulation.components.IEntity {
        {abstract} + IsActive()
        {abstract} + IsAlive()
        {abstract} + OnActivated()
        {abstract} + OnActivating()
        {abstract} + OnCreated()
        {abstract} + OnCreating()
        {abstract} + OnDeactivated()
        {abstract} + OnDeactivating()
        {abstract} + OnInitialized()
        {abstract} + OnInitializing()
        {abstract} + OnTerminating()
        {abstract} + RandomGenerator()
        {abstract} + activate()
        {abstract} + deactivate()
        {abstract} + getChildren()
        {abstract} + getFullName()
        {abstract} + getParent()
        {abstract} + setEngine()
    }
  }
  

  namespace enstabretagne.simulation.components {
    interface enstabretagne.simulation.components.IScenarioIdProvider {
        {abstract} + getScenarioId()
    }
  }
  

  namespace enstabretagne.simulation.components {
    interface enstabretagne.simulation.components.ISimEntity {
    }
  }
  

  namespace enstabretagne.simulation.components {
    class enstabretagne.simulation.components.ScenarioId {
        {static} + ScenarioID_NULL : ScenarioId
        - repliqueNumber : long
        - scenarioId : String
        + ScenarioId()
        + ScenarioId()
        + getRepliqueNumber()
        + getScenarioId()
        + setRepliqueNumber()
        + setScenarioId()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
