@startuml

title __NOTIFICATIONS's Class Diagram__\n

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.NotifyLogicalDateChange {
          {abstract} + notifyLogicalDateChange()
      }
    }
  }
  

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.NotifySimEngineEvent {
          {abstract} + notifySimEngineEvent()
      }
    }
  }
  

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.NotifySimEvent {
          {abstract} + notifySimEvent()
      }
    }
  }
  

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.NotifySimTimeEvent {
          {abstract} + notifySimTimeEvent()
      }
    }
  }
  

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.SimEngineEvent {
          {abstract} + simEngineEvent()
      }
    }
  }
  

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.SimObjectActivationChangedEventHandler {
          {abstract} + simObjectActivationChanged()
      }
    }
  }
  

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.SimObjectAddedListener {
          {abstract} + SimObjectAdded()
      }
    }
  }
  

  namespace enstabretagne.simulation.core {
    namespace notifications {
      interface enstabretagne.simulation.core.notifications.SimObjectRemovedListener {
          {abstract} + SimObjectRemoved()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
