@startuml

title __MONITOR's Class Diagram__\n

  namespace enstabretagne.monitor {
    interface enstabretagne.monitor.Contrat3D {
        {abstract} + contrat()
    }
  }
  

  namespace enstabretagne.monitor {
    interface enstabretagne.monitor.IDrawAction {
        {abstract} + getGeneral3DSettings()
        {abstract} + init()
        {abstract} + update()
    }
  }
  

  namespace enstabretagne.monitor {
    interface enstabretagne.monitor.IExperiencePlan {
        {abstract} + getInitialSeed()
        {abstract} + getListeScenarios()
        {abstract} + getNombreRepliques()
    }
  }
  

  namespace enstabretagne.monitor {
    interface enstabretagne.monitor.IMonitor {
        {abstract} + exit()
        {abstract} + getLogicalTimeSpeed()
        {abstract} + loadExperiencePlan()
        {abstract} + loadExperiencePlanFromSettings()
        {abstract} + pause()
        {abstract} + run()
        {abstract} + runPlan()
        {abstract} + selectNextScenario()
        {abstract} + selectScenario()
        {abstract} + setLogicalTimeSpeed()
        {abstract} + stop()
    }
  }
  

  namespace enstabretagne.monitor {
    class enstabretagne.monitor.Monitor3DMessages {
        {static} + LoggerParsingFailed : String
        {static} + Monitor3DSettingsDirNotFound : String
        {static} + Monitor3DSettingsFileNotFound : String
        {static} + Obj3DPasBonContrat3D : String
        {static} + PasContrat : String
        {static} + representation3DNonTrouve : String
        {static} + type3DPasConstructeurAvec3DSettings : String
        {static} + type3DPasDrawAction : String
        {static} + typeEntiteNonTrouve : String
        {static} + typeEntitePasSimEntity : String
    }
  }
  

  namespace enstabretagne.monitor {
    class enstabretagne.monitor.Monitor3DSettings {
        + entiteASuivre : String
        + frameparseconde : double
        + mappingClasse2Representation3D : List<ObjTo3DMappingSettings>
        {static} + settings : Monitor3DSettings
        {static} - monitor3DSettingsFileName : String
        + Monitor3DSettings()
    }
  }
  

  namespace enstabretagne.monitor {
    class enstabretagne.monitor.ObjTo3DMappingSettings {
        + Representation3DAMapper : String
        + classeObjetAMapper : String
        + level4Trasparency : int
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
