@startuml

title __TIME's Class Diagram__\n

  namespace enstabretagne.base {
    namespace time {
      class enstabretagne.base.time.LogicalDateTime {
          {static} + MaxValue : LogicalDateTime
          {static} + MinValue : LogicalDateTime
          {static} + UNDEFINED : LogicalDateTime
          {static} + Zero : LogicalDateTime
          {static} + logicalDateFormatter : DateTimeFormatter
          {static} + logicalDateTimeFormatter : DateTimeFormatter
          {static} + logicalTimeFormatter : DateTimeFormatter
          {static} + wellFormedDateSample : String
          ~ isDefined : boolean
          ~ logicalDate : LocalDateTime
          {static} + EstBienStructuree()
          {static} + LogicalDateFrom()
          + LogicalDateTime()
          + add()
          {static} + add()
          + compareTo()
          + getCopy()
          + getDayOfWeek()
          + replaceBy()
          + soustract()
          + toString()
          + truncateToDays()
          + truncateToHours()
          + truncateToMinutes()
          + truncateToYears()
          - LogicalDateTime()
          - LogicalDateTime()
      }
    }
  }
  

  namespace enstabretagne.base {
    namespace time {
      class enstabretagne.base.time.LogicalDuration {
          {static} + MAX_VALUE : LogicalDuration
          {static} + POSITIVE_INFINITY : LogicalDuration
          {static} + TickValue : LogicalDuration
          {static} + ZERO : LogicalDuration
          {static} + f : DecimalFormat
          ~ logicalDuration : Duration
          + DoubleValue()
          {static} + Max()
          {static} + Quantify()
          + add()
          + compareTo()
          {static} + fromString()
          + getTotalOfHours()
          + getTotalOfMinutes()
          + getTotalOfSeconds()
          + mult()
          {static} + ofDay()
          {static} + ofHours()
          {static} + ofMillis()
          {static} + ofMinutes()
          {static} + ofNanos()
          {static} + ofSeconds()
          {static} + soustract()
          + toString()
          - LogicalDuration()
      }
    }
  }
  

  namespace enstabretagne.base {
    namespace time {
      enum TimeUnits {
        Annee
        Heure
        Milliseconde
        Minute
        Seconde
        name
      }
    }
  }
  

  enstabretagne.base.time.LogicalDateTime .up.|> java.lang.Comparable
  enstabretagne.base.time.LogicalDuration .up.|> java.lang.Comparable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
