@startuml

title __CORE's Class Diagram__\n

  namespace enstabretagne.simulation.core {
    class enstabretagne.simulation.core.EngineActivity {
        {static} + Finalizing : EngineActivity
        {static} + Initializing : EngineActivity
        {static} + NotInitialized : EngineActivity
        {static} + PausedWaiting : EngineActivity
        {static} + TimeEvent : EngineActivity
        {static} + Unknown : EngineActivity
        - engineActivityValue : int
        - name : String
        + EngineActivity()
        + engineActivityValue()
        + getName()
        + toString()
    }
  }
  

  namespace enstabretagne.simulation.core {
    enum EngineInterruptReason {
      ByDate
      ByMaxDate
      ByNone
      ByUser
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.IEngine {
        {abstract} + AddSimObjectAddedListener()
        {abstract} + RemoveSimObjectAddedListener()
        {abstract} + SimulationDate()
        {abstract} + getRandomGenerator()
        {abstract} + requestSimObject()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.IScenario {
        {abstract} + getEndDateTime()
        {abstract} + getName()
        {abstract} + getScenarioId()
        {abstract} + getSeed()
        {abstract} + getStartDateTime()
        {abstract} + setEngine()
        {abstract} + terminate()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.IScenarioInstance {
        {abstract} + getScenarioInstance()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.ISimEngine {
        {abstract} + OnEventPosted()
        {abstract} + OnEventUnPosted()
        {abstract} + OnSimObjectAdded()
        {abstract} + OnSimObjectRemoved()
        {abstract} + activateSimulation()
        {abstract} + deactivateSimulation()
        {abstract} + init()
        {abstract} + interrupt()
        {abstract} + simulate()
        {abstract} + terminate()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.ISimEvent {
        {abstract} + Owner()
        {abstract} + Process()
        {abstract} + ScheduleDate()
        {abstract} + TimeEventLine()
        {abstract} + initialize()
        {abstract} + resetProcessDate()
        {abstract} + terminate()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.ISimObject {
        {abstract} + CurrentDate()
        {abstract} + Post()
        {abstract} + Post()
        {abstract} + Post()
        {abstract} + UnPost()
        {abstract} + UnPostAllEvents()
        {abstract} + getName()
        {abstract} + getSimObjID()
        {abstract} + interruptEngineByDate()
        {abstract} + terminate()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.ISimObjectDictionary {
        {abstract} + Add()
        {abstract} + AddSimObjectAddedListener()
        {abstract} + AddSimObjectRemovedListener()
        {abstract} + Remove()
        {abstract} + RemoveSimObjectAddedListener()
        {abstract} + RemoveSimObjectRemovedListener()
        {abstract} + RetreiveSimObject()
        {abstract} + WriteObjectTypeDictionary()
        {abstract} + getKnownSimObjects()
        {abstract} + getSimObjectTypeFrom()
        {abstract} + initialize()
        {abstract} + requestSimObject()
        {abstract} + terminate()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.ISimObjectType {
        {abstract} + getObjectInstances()
        {abstract} + terminate()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.ISimTimeEvent {
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.ISimulationDateProvider {
        {abstract} + SimulationDate()
    }
  }
  

  namespace enstabretagne.simulation.core {
    interface enstabretagne.simulation.core.SimObjectRequest {
        {abstract} + filter()
    }
  }
  

  namespace enstabretagne.simulation.core {
    class enstabretagne.simulation.core.SortedList {
        ~ l : List<T>
        + SortedList()
        + add()
        + clear()
        + contains()
        + first()
        + iterator()
        + remove()
        + size()
    }
  }
  

  enstabretagne.simulation.core.SortedList .up.|> java.lang.Iterable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
