@startuml

title __LOGGERIMPL's Class Diagram__\n

  namespace enstabretagne.base {
    namespace logger {
      namespace loggerimpl {
        abstract class enstabretagne.base.logger.loggerimpl.AbstractLogger {
            + checkLoggerConf()
        }
      }
    }
  }
  

  namespace enstabretagne.base {
    namespace logger {
      namespace loggerimpl {
        class enstabretagne.base.logger.loggerimpl.LoggerConf {
            + parametres : HashMap<String, String>
            + LoggerConf()
            + checkLoggerConf()
        }
      }
    }
  }
  

  namespace enstabretagne.base {
    namespace logger {
      namespace loggerimpl {
        class enstabretagne.base.logger.loggerimpl.ObjectAnalyseForLog {
            ~ o : Object
            ~ records : String[]
            + ObjectAnalyseForLog()
            + getClassement()
            + getObjectType()
            + getRecords()
            + getTitles()
            + toString()
        }
      }
    }
  }
  

  namespace enstabretagne.base {
    namespace logger {
      namespace loggerimpl {
        class enstabretagne.base.logger.loggerimpl.TypeAnalyseForLog {
            ~ classement : String
            ~ mL : HashMap<String, Method>
            ~ titles : String[]
            + TypeAnalyseForLog()
            + getClassement()
            + getTitles()
        }
      }
    }
  }
  

  enstabretagne.base.logger.loggerimpl.AbstractLogger .up.|> enstabretagne.base.logger.ILogger
  enstabretagne.base.logger.loggerimpl.ObjectAnalyseForLog .up.|> enstabretagne.base.logger.IRecordable
  enstabretagne.base.logger.loggerimpl.ObjectAnalyseForLog o-- enstabretagne.base.logger.loggerimpl.TypeAnalyseForLog : to


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
